---
- name: generate SSL key and certificate
  command: openssl req -x509 -nodes -days 365
             -newkey rsa:2048
             -keyout /etc/ssl/{{ app_name }}.key
             -out /etc/ssl/{{ app_name }}.crt
             -subj '{{ ssl_cert_subj }}'
  args:
    creates: /etc/ssl/{{ app_name }}.*
  notify: "restart web services"
  become: True

