---
- name: restart uwsgi
  service: name=uwsgi state=restarted
  listen: "restart web stack"
  become: True

- name: restart nginx
  service: name=nginx state=restarted
  listen: "restart web stack"
  become: True

