---
## this is an optional access key that must be
##   included in the url as ?key=<value>, in lieu
##   of an .htaccess file or some other protection
access_key: mykey

## SSL certificate Subject information
ssl_cert_country: US
ssl_cert_state: New York
ssl_cert_city: New York
ssl_cert_organization: "{{ app_name }}"
ssl_cert_org_unit: "{{ app_name }}"
ssl_cert_subj: >
  /C={{ ssl_cert_country }}/ST={{ ssl_cert_state }}/L={{ ssl_cert_city }}/O={{ ssl_cert_organization }}/OU={{ ssl_cert_org_unit }}/CN={{ ansible_fqdn }}/emailAddress=admin@{{ ansible_fqdn }}

mode: Debug # or Prod; note: case-sensitive
deploy_user: ubuntu
app_name: expense-www
cgi_path: "/expense"
log_path: "/var/log"

## PostgreSQL database connection info; leave
##   db_host and db_port blank/null if running
##   on same server as web host
db_name: "{{ app_name }}"
db_host:
db_port:
db_user: "{{ ansible_ssh_user }}"
db_pass:
